#!/bin/bash
# Database Setup Script (Run after supervisor installs PostgreSQL and creates your user)

set -e  # Exit on error

echo "======================================================================"
echo "  IoV Digital Twin - Database Setup"
echo "======================================================================"
echo ""

# Configuration
DB_NAME="iov_digital_twin"
DB_USER="${USER}"  # Current username (mihiraja)

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo "❌ ERROR: PostgreSQL is not installed."
    echo "   Please ask your supervisor to run the installation commands first."
    echo "   See INSTALLATION_REQUIREMENTS.md"
    exit 1
fi

# Check if Redis is installed
if ! command -v redis-cli &> /dev/null; then
    echo "⚠️  WARNING: Redis is not installed."
    echo "   Redis features will be disabled."
    REDIS_INSTALLED=false
else
    REDIS_INSTALLED=true
fi

echo "📋 Configuration:"
echo "   Database Name: $DB_NAME"
echo "   Database User: $DB_USER"
echo "   PostgreSQL: ✅ Installed"
if [ "$REDIS_INSTALLED" = true ]; then
    echo "   Redis: ✅ Installed"
else
    echo "   Redis: ❌ Not installed"
fi
echo ""

# Test PostgreSQL connection
echo "🔍 Testing PostgreSQL connection..."
if psql -U "$DB_USER" -d postgres -c "\q" 2>/dev/null; then
    echo "✅ PostgreSQL user '$DB_USER' exists and can connect"
else
    echo "❌ ERROR: Cannot connect to PostgreSQL as user '$DB_USER'"
    echo ""
    echo "Your supervisor needs to create your PostgreSQL user first:"
    echo "  sudo -u postgres psql -c \"CREATE USER $DB_USER WITH CREATEDB ENCRYPTED PASSWORD 'password';\""
    exit 1
fi

# Check if database already exists
echo ""
echo "🔍 Checking if database exists..."
if psql -U "$DB_USER" -d postgres -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
    echo "⚠️  Database '$DB_NAME' already exists"
    read -p "   Do you want to recreate it? (yes/no): " -r
    if [[ $REPLY =~ ^[Yy]es$ ]]; then
        echo "   Dropping existing database..."
        psql -U "$DB_USER" -d postgres -c "DROP DATABASE $DB_NAME;"
        echo "   Creating new database..."
        psql -U "$DB_USER" -d postgres -c "CREATE DATABASE $DB_NAME;"
        echo "✅ Database recreated"
    else
        echo "   Keeping existing database"
    fi
else
    echo "📦 Creating database '$DB_NAME'..."
    psql -U "$DB_USER" -d postgres -c "CREATE DATABASE $DB_NAME;"
    echo "✅ Database created"
fi

# Update .env file
echo ""
echo "📝 Updating .env file..."
read -sp "Enter PostgreSQL password for user '$DB_USER': " DB_PASSWORD
echo ""

# Backup existing .env if it exists
if [ -f .env ]; then
    cp .env .env.backup
    echo "   Backed up existing .env to .env.backup"
fi

# Update or create .env file
cat > .env << EOF
# Environment Configuration for IoV Digital Twin Task Offloading
# Auto-generated on $(date)

# PostgreSQL Database Connection
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME?sslmode=disable

# Redis Connection
REDIS_HOST=localhost
REDIS_PORT=6379

# Generated by setup_database.sh
EOF

echo "✅ .env file updated"

# Test database connection
echo ""
echo "🔍 Testing database connection..."
if psql -U "$DB_USER" -d "$DB_NAME" -c "SELECT version();" > /dev/null 2>&1; then
    echo "✅ Successfully connected to database '$DB_NAME'"
else
    echo "❌ Failed to connect to database"
    exit 1
fi

# Test Redis connection if installed
if [ "$REDIS_INSTALLED" = true ]; then
    echo ""
    echo "🔍 Testing Redis connection..."
    if redis-cli ping > /dev/null 2>&1; then
        echo "✅ Redis is running and responding"
    else
        echo "⚠️  Redis is installed but not running"
        echo "   Your supervisor may need to start it:"
        echo "   sudo systemctl start redis-server"
    fi
fi

# Update omnetpp.ini to enable Redis if available
if [ "$REDIS_INSTALLED" = true ]; then
    echo ""
    echo "📝 Enabling Redis in omnetpp.ini..."
    sed -i 's/^\*.rsu\[\*\]\.appl\.useRedis = false/\*.rsu[*].appl.useRedis = true/' omnetpp.ini
    echo "✅ Redis enabled in configuration"
fi

echo ""
echo "======================================================================"
echo "  ✅ Database setup complete!"
echo "======================================================================"
echo ""
echo "Next steps:"
echo "  1. Review .env file to verify settings"
echo "  2. Start SUMO: sumo -c erlangen.sumo.cfg --remote-port 9999"
echo "  3. Run simulation from OMNeT++ IDE or: ./run.sh"
echo ""
echo "Connection string: postgresql://$DB_USER:***@localhost:5432/$DB_NAME"
echo ""
