//
// Generated file, do not edit! Created by opp_msgtool 6.1 from TaskMetadataMessage.msg.
//

#ifndef __VEINS_TASKMETADATAMESSAGE_M_H
#define __VEINS_TASKMETADATAMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class TaskMetadataMessage;
class TaskCompletionMessage;
class TaskFailureMessage;
class VehicleResourceStatusMessage;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>TaskMetadataMessage.msg:13</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Metadata Message - Sent from vehicle to RSU when task is generated
 * //
 * packet TaskMetadataMessage extends BaseFrame1609_4
 * {
 *     // Task Identification
 *     string task_id;              // Unique task identifier
 *     string vehicle_id;           // Originating vehicle ID
 * 
 *     // Task Characteristics
 *     uint64_t task_size_bytes;    // Memory footprint (D_task)
 *     uint64_t cpu_cycles;         // Required CPU cycles (C_task)
 * 
 *     // Timing Information
 *     double created_time;         // SimTime when task was generated
 *     double deadline_seconds;     // Relative deadline (e.g., 0.3 seconds)
 *     double received_time = 0;    // Assigned by RSU upon reception
 * 
 *     // QoS and Priority
 *     double qos_value;            // Quality of Service (0.0 - 1.0)
 * }
 * </pre>
 */
class TaskMetadataMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    uint64_t task_size_bytes = 0;
    uint64_t cpu_cycles = 0;
    double created_time = 0;
    double deadline_seconds = 0;
    double received_time = 0;
    double qos_value = 0;

  private:
    void copy(const TaskMetadataMessage& other);

  protected:
    bool operator==(const TaskMetadataMessage&) = delete;

  public:
    TaskMetadataMessage(const char *name=nullptr, short kind=0);
    TaskMetadataMessage(const TaskMetadataMessage& other);
    virtual ~TaskMetadataMessage();
    TaskMetadataMessage& operator=(const TaskMetadataMessage& other);
    virtual TaskMetadataMessage *dup() const override {return new TaskMetadataMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual uint64_t getTask_size_bytes() const;
    virtual void setTask_size_bytes(uint64_t task_size_bytes);

    virtual uint64_t getCpu_cycles() const;
    virtual void setCpu_cycles(uint64_t cpu_cycles);

    virtual double getCreated_time() const;
    virtual void setCreated_time(double created_time);

    virtual double getDeadline_seconds() const;
    virtual void setDeadline_seconds(double deadline_seconds);

    virtual double getReceived_time() const;
    virtual void setReceived_time(double received_time);

    virtual double getQos_value() const;
    virtual void setQos_value(double qos_value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskMetadataMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskMetadataMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:34</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Completion Message - Sent from vehicle to RSU when task completes
 * //
 * packet TaskCompletionMessage extends BaseFrame1609_4
 * {
 *     string task_id;              // Task identifier
 *     string vehicle_id;           // Originating vehicle ID
 *     double completion_time;      // When task completed
 *     double processing_time;      // Actual processing duration
 *     bool completed_on_time;      // True if completed before deadline
 *     double cpu_allocated;        // Average CPU allocated during processing
 * }
 * </pre>
 */
class TaskCompletionMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    double completion_time = 0;
    double processing_time = 0;
    bool completed_on_time = false;
    double cpu_allocated = 0;

  private:
    void copy(const TaskCompletionMessage& other);

  protected:
    bool operator==(const TaskCompletionMessage&) = delete;

  public:
    TaskCompletionMessage(const char *name=nullptr, short kind=0);
    TaskCompletionMessage(const TaskCompletionMessage& other);
    virtual ~TaskCompletionMessage();
    TaskCompletionMessage& operator=(const TaskCompletionMessage& other);
    virtual TaskCompletionMessage *dup() const override {return new TaskCompletionMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getCompletion_time() const;
    virtual void setCompletion_time(double completion_time);

    virtual double getProcessing_time() const;
    virtual void setProcessing_time(double processing_time);

    virtual bool getCompleted_on_time() const;
    virtual void setCompleted_on_time(bool completed_on_time);

    virtual double getCpu_allocated() const;
    virtual void setCpu_allocated(double cpu_allocated);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskCompletionMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskCompletionMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:46</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Failure Message - Sent from vehicle to RSU when task fails/is rejected
 * //
 * packet TaskFailureMessage extends BaseFrame1609_4
 * {
 *     string task_id;              // Task identifier
 *     string vehicle_id;           // Originating vehicle ID
 *     double failure_time;         // When task failed/was rejected
 *     string failure_reason;       // "DEADLINE_MISSED", "REJECTED_QUEUE_FULL", "REJECTED_INFEASIBLE"
 *     double wasted_time;          // Time spent before failure
 * }
 * </pre>
 */
class TaskFailureMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    double failure_time = 0;
    ::omnetpp::opp_string failure_reason;
    double wasted_time = 0;

  private:
    void copy(const TaskFailureMessage& other);

  protected:
    bool operator==(const TaskFailureMessage&) = delete;

  public:
    TaskFailureMessage(const char *name=nullptr, short kind=0);
    TaskFailureMessage(const TaskFailureMessage& other);
    virtual ~TaskFailureMessage();
    TaskFailureMessage& operator=(const TaskFailureMessage& other);
    virtual TaskFailureMessage *dup() const override {return new TaskFailureMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getFailure_time() const;
    virtual void setFailure_time(double failure_time);

    virtual const char * getFailure_reason() const;
    virtual void setFailure_reason(const char * failure_reason);

    virtual double getWasted_time() const;
    virtual void setWasted_time(double wasted_time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskFailureMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskFailureMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:57</tt> by opp_msgtool.
 * <pre>
 * //
 * // Vehicle Resource Status Message - Periodic heartbeat from vehicle to RSU
 * //
 * packet VehicleResourceStatusMessage extends BaseFrame1609_4
 * {
 *     string vehicle_id;           // Vehicle identifier
 * 
 *     // Vehicle State
 *     double pos_x;                // Position X
 *     double pos_y;                // Position Y
 *     double speed;                // Current speed
 * 
 *     // Resource Information
 *     double cpu_total;            // Total CPU capacity (Hz)
 *     double cpu_allocable;        // CPU available for tasks (after reservation)
 *     double cpu_available;        // Currently available CPU (Hz)
 *     double cpu_utilization;      // CPU utilization percentage (0-100)
 * 
 *     double mem_total;            // Total memory (bytes)
 *     double mem_available;        // Available memory (bytes)
 *     double mem_utilization;      // Memory utilization percentage (0-100)
 * 
 *     // Task Queue Status
 *     uint32_t tasks_generated;    // Total tasks generated
 *     uint32_t tasks_completed_on_time;  // Tasks completed before deadline
 *     uint32_t tasks_completed_late;     // Tasks completed after deadline (soft miss)
 *     uint32_t tasks_failed;       // Tasks that missed deadline (hard miss)
 *     uint32_t tasks_rejected;     // Tasks rejected (queue full/infeasible)
 *     uint32_t current_queue_length;     // Current pending tasks
 *     uint32_t current_processing_count; // Currently processing tasks
 * 
 *     // Performance Metrics
 *     double avg_completion_time;  // Average task completion time
 *     double deadline_miss_ratio;  // Ratio of missed deadlines
 * }
 * </pre>
 */
class VehicleResourceStatusMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string vehicle_id;
    double pos_x = 0;
    double pos_y = 0;
    double speed = 0;
    double cpu_total = 0;
    double cpu_allocable = 0;
    double cpu_available = 0;
    double cpu_utilization = 0;
    double mem_total = 0;
    double mem_available = 0;
    double mem_utilization = 0;
    uint32_t tasks_generated = 0;
    uint32_t tasks_completed_on_time = 0;
    uint32_t tasks_completed_late = 0;
    uint32_t tasks_failed = 0;
    uint32_t tasks_rejected = 0;
    uint32_t current_queue_length = 0;
    uint32_t current_processing_count = 0;
    double avg_completion_time = 0;
    double deadline_miss_ratio = 0;

  private:
    void copy(const VehicleResourceStatusMessage& other);

  protected:
    bool operator==(const VehicleResourceStatusMessage&) = delete;

  public:
    VehicleResourceStatusMessage(const char *name=nullptr, short kind=0);
    VehicleResourceStatusMessage(const VehicleResourceStatusMessage& other);
    virtual ~VehicleResourceStatusMessage();
    VehicleResourceStatusMessage& operator=(const VehicleResourceStatusMessage& other);
    virtual VehicleResourceStatusMessage *dup() const override {return new VehicleResourceStatusMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getPos_x() const;
    virtual void setPos_x(double pos_x);

    virtual double getPos_y() const;
    virtual void setPos_y(double pos_y);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getCpu_total() const;
    virtual void setCpu_total(double cpu_total);

    virtual double getCpu_allocable() const;
    virtual void setCpu_allocable(double cpu_allocable);

    virtual double getCpu_available() const;
    virtual void setCpu_available(double cpu_available);

    virtual double getCpu_utilization() const;
    virtual void setCpu_utilization(double cpu_utilization);

    virtual double getMem_total() const;
    virtual void setMem_total(double mem_total);

    virtual double getMem_available() const;
    virtual void setMem_available(double mem_available);

    virtual double getMem_utilization() const;
    virtual void setMem_utilization(double mem_utilization);

    virtual uint32_t getTasks_generated() const;
    virtual void setTasks_generated(uint32_t tasks_generated);

    virtual uint32_t getTasks_completed_on_time() const;
    virtual void setTasks_completed_on_time(uint32_t tasks_completed_on_time);

    virtual uint32_t getTasks_completed_late() const;
    virtual void setTasks_completed_late(uint32_t tasks_completed_late);

    virtual uint32_t getTasks_failed() const;
    virtual void setTasks_failed(uint32_t tasks_failed);

    virtual uint32_t getTasks_rejected() const;
    virtual void setTasks_rejected(uint32_t tasks_rejected);

    virtual uint32_t getCurrent_queue_length() const;
    virtual void setCurrent_queue_length(uint32_t current_queue_length);

    virtual uint32_t getCurrent_processing_count() const;
    virtual void setCurrent_processing_count(uint32_t current_processing_count);

    virtual double getAvg_completion_time() const;
    virtual void setAvg_completion_time(double avg_completion_time);

    virtual double getDeadline_miss_ratio() const;
    virtual void setDeadline_miss_ratio(double deadline_miss_ratio);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VehicleResourceStatusMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VehicleResourceStatusMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::TaskMetadataMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskMetadataMessage*>(ptr.get<cObject>()); }
template<> inline veins::TaskCompletionMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskCompletionMessage*>(ptr.get<cObject>()); }
template<> inline veins::TaskFailureMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskFailureMessage*>(ptr.get<cObject>()); }
template<> inline veins::VehicleResourceStatusMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::VehicleResourceStatusMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_TASKMETADATAMESSAGE_M_H

