//
// Generated file, do not edit! Created by opp_msgtool 6.1 from TaskMetadataMessage.msg.
//

#ifndef __VEINS_TASKMETADATAMESSAGE_M_H
#define __VEINS_TASKMETADATAMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class TaskMetadataMessage;
class ObjectDetectionDataMessage;
class TaskCompletionMessage;
class TaskFailureMessage;
class VehicleResourceStatusMessage;
class OffloadingRequestMessage;
class OffloadingDecisionMessage;
class TaskOffloadPacket;
class TaskResultMessage;
class TaskOffloadingEvent;
class VehicleDetailInBroadcast;
class RSUStatusBroadcastMessage;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>TaskMetadataMessage.msg:13</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Metadata Message - Sent from vehicle to RSU when task is generated
 * //
 * packet TaskMetadataMessage extends BaseFrame1609_4
 * {
 *     // Task Identification
 *     string task_id;              // Unique task identifier
 *     string vehicle_id;           // Originating vehicle ID
 * 
 *     // Task Characteristics
 *     uint64_t task_size_bytes;    // Legacy payload size field (= input_size_bytes)
 *     uint64_t mem_footprint_bytes; // Working memory footprint (D_task)
 *     uint64_t cpu_cycles;         // Required CPU cycles (C_task)
 * 
 *     // Timing Information
 *     double created_time;         // SimTime when task was generated
 *     double deadline_seconds;     // Relative deadline (e.g., 0.3 seconds)
 *     double received_time = 0;    // Assigned by RSU upon reception
 * 
 *     // QoS and Priority
 *     double qos_value;            // Quality of Service (0.0 - 1.0)
 * 
 *     // Task Profile Fields (set when is_profile_task = true)
 *     bool is_profile_task = false;     // True if generated from TaskProfile taxonomy
 *     string task_type_name;            // Human-readable type: "LOCAL_OBJECT_DETECTION", etc.
 *     int task_type_id = 0;             // Numeric TaskType enum value
 *     uint64_t input_size_bytes = 0;    // Input data size (may differ from task_size_bytes)
 *     uint64_t output_size_bytes = 0;   // Expected output size
 *     bool is_offloadable = true;       // False for safety-critical local-only tasks
 *     bool is_safety_critical = false;  // True for LOCAL_OBJECT_DETECTION
 *     int priority_level = 2;           // PriorityLevel enum (0=LOW, 1=MEDIUM, 2=HIGH, 3=SAFETY_CRITICAL)
 * }
 * </pre>
 */
class TaskMetadataMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    uint64_t task_size_bytes = 0;
    uint64_t mem_footprint_bytes = 0;
    uint64_t cpu_cycles = 0;
    double created_time = 0;
    double deadline_seconds = 0;
    double received_time = 0;
    double qos_value = 0;
    bool is_profile_task = false;
    ::omnetpp::opp_string task_type_name;
    int task_type_id = 0;
    uint64_t input_size_bytes = 0;
    uint64_t output_size_bytes = 0;
    bool is_offloadable = true;
    bool is_safety_critical = false;
    int priority_level = 2;

  private:
    void copy(const TaskMetadataMessage& other);

  protected:
    bool operator==(const TaskMetadataMessage&) = delete;

  public:
    TaskMetadataMessage(const char *name=nullptr, short kind=0);
    TaskMetadataMessage(const TaskMetadataMessage& other);
    virtual ~TaskMetadataMessage();
    TaskMetadataMessage& operator=(const TaskMetadataMessage& other);
    virtual TaskMetadataMessage *dup() const override {return new TaskMetadataMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual uint64_t getTask_size_bytes() const;
    virtual void setTask_size_bytes(uint64_t task_size_bytes);

    virtual uint64_t getMem_footprint_bytes() const;
    virtual void setMem_footprint_bytes(uint64_t mem_footprint_bytes);

    virtual uint64_t getCpu_cycles() const;
    virtual void setCpu_cycles(uint64_t cpu_cycles);

    virtual double getCreated_time() const;
    virtual void setCreated_time(double created_time);

    virtual double getDeadline_seconds() const;
    virtual void setDeadline_seconds(double deadline_seconds);

    virtual double getReceived_time() const;
    virtual void setReceived_time(double received_time);

    virtual double getQos_value() const;
    virtual void setQos_value(double qos_value);

    virtual bool getIs_profile_task() const;
    virtual void setIs_profile_task(bool is_profile_task);

    virtual const char * getTask_type_name() const;
    virtual void setTask_type_name(const char * task_type_name);

    virtual int getTask_type_id() const;
    virtual void setTask_type_id(int task_type_id);

    virtual uint64_t getInput_size_bytes() const;
    virtual void setInput_size_bytes(uint64_t input_size_bytes);

    virtual uint64_t getOutput_size_bytes() const;
    virtual void setOutput_size_bytes(uint64_t output_size_bytes);

    virtual bool getIs_offloadable() const;
    virtual void setIs_offloadable(bool is_offloadable);

    virtual bool getIs_safety_critical() const;
    virtual void setIs_safety_critical(bool is_safety_critical);

    virtual int getPriority_level() const;
    virtual void setPriority_level(int priority_level);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskMetadataMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskMetadataMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:45</tt> by opp_msgtool.
 * <pre>
 * //
 * // Object Detection Data Message - Vehicle → Vehicle broadcast (cooperative perception)
 * //
 * packet ObjectDetectionDataMessage extends BaseFrame1609_4
 * {
 *     string vehicle_id;           // Sender vehicle ID
 *     double timestamp;            // When detection was produced (sim time)
 *     uint64_t data_size_bytes;    // Size of object list payload
 *     string payload_tag;          // Lightweight tag for tracing (no raw data)
 * }
 * </pre>
 */
class ObjectDetectionDataMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string vehicle_id;
    double timestamp = 0;
    uint64_t data_size_bytes = 0;
    ::omnetpp::opp_string payload_tag;

  private:
    void copy(const ObjectDetectionDataMessage& other);

  protected:
    bool operator==(const ObjectDetectionDataMessage&) = delete;

  public:
    ObjectDetectionDataMessage(const char *name=nullptr, short kind=0);
    ObjectDetectionDataMessage(const ObjectDetectionDataMessage& other);
    virtual ~ObjectDetectionDataMessage();
    ObjectDetectionDataMessage& operator=(const ObjectDetectionDataMessage& other);
    virtual ObjectDetectionDataMessage *dup() const override {return new ObjectDetectionDataMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);

    virtual uint64_t getData_size_bytes() const;
    virtual void setData_size_bytes(uint64_t data_size_bytes);

    virtual const char * getPayload_tag() const;
    virtual void setPayload_tag(const char * payload_tag);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ObjectDetectionDataMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ObjectDetectionDataMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:55</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Completion Message - Sent from vehicle to RSU when task completes
 * //
 * packet TaskCompletionMessage extends BaseFrame1609_4
 * {
 *     string task_id;              // Task identifier
 *     string vehicle_id;           // Originating vehicle ID
 *     double completion_time;      // When task completed
 *     double processing_time;      // Actual processing duration
 *     bool completed_on_time;      // True if completed before deadline
 *     double cpu_allocated;        // Average CPU allocated during processing
 * 
 *     // Local-execution metadata (set when is_local_execution = true)
 *     // Required by RSU to write task:{id}:local_result to Redis without a prior request hash
 *     bool is_local_execution = false;       // True when vehicle executed the task locally
 *     string task_type_name;                 // e.g. "LOCAL_OBJECT_DETECTION"
 *     double qos_value = 0.0;               // QoS level (0.0–1.0) of the completed task
 *     double deadline_seconds = 0.0;        // Original deadline of the completed task
 *     string failure_reason;                 // "NONE", "DEADLINE_MISSED", etc.
 * }
 * </pre>
 */
class TaskCompletionMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    double completion_time = 0;
    double processing_time = 0;
    bool completed_on_time = false;
    double cpu_allocated = 0;
    bool is_local_execution = false;
    ::omnetpp::opp_string task_type_name;
    double qos_value = 0.0;
    double deadline_seconds = 0.0;
    ::omnetpp::opp_string failure_reason;

  private:
    void copy(const TaskCompletionMessage& other);

  protected:
    bool operator==(const TaskCompletionMessage&) = delete;

  public:
    TaskCompletionMessage(const char *name=nullptr, short kind=0);
    TaskCompletionMessage(const TaskCompletionMessage& other);
    virtual ~TaskCompletionMessage();
    TaskCompletionMessage& operator=(const TaskCompletionMessage& other);
    virtual TaskCompletionMessage *dup() const override {return new TaskCompletionMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getCompletion_time() const;
    virtual void setCompletion_time(double completion_time);

    virtual double getProcessing_time() const;
    virtual void setProcessing_time(double processing_time);

    virtual bool getCompleted_on_time() const;
    virtual void setCompleted_on_time(bool completed_on_time);

    virtual double getCpu_allocated() const;
    virtual void setCpu_allocated(double cpu_allocated);

    virtual bool getIs_local_execution() const;
    virtual void setIs_local_execution(bool is_local_execution);

    virtual const char * getTask_type_name() const;
    virtual void setTask_type_name(const char * task_type_name);

    virtual double getQos_value() const;
    virtual void setQos_value(double qos_value);

    virtual double getDeadline_seconds() const;
    virtual void setDeadline_seconds(double deadline_seconds);

    virtual const char * getFailure_reason() const;
    virtual void setFailure_reason(const char * failure_reason);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskCompletionMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskCompletionMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:75</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Failure Message - Sent from vehicle to RSU when task fails/is rejected
 * //
 * packet TaskFailureMessage extends BaseFrame1609_4
 * {
 *     string task_id;              // Task identifier
 *     string vehicle_id;           // Originating vehicle ID
 *     double failure_time;         // When task failed/was rejected
 *     string failure_reason;       // "DEADLINE_MISSED", "REJECTED_QUEUE_FULL", "REJECTED_INFEASIBLE"
 *     double wasted_time;          // Time spent before failure
 * }
 * </pre>
 */
class TaskFailureMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    double failure_time = 0;
    ::omnetpp::opp_string failure_reason;
    double wasted_time = 0;

  private:
    void copy(const TaskFailureMessage& other);

  protected:
    bool operator==(const TaskFailureMessage&) = delete;

  public:
    TaskFailureMessage(const char *name=nullptr, short kind=0);
    TaskFailureMessage(const TaskFailureMessage& other);
    virtual ~TaskFailureMessage();
    TaskFailureMessage& operator=(const TaskFailureMessage& other);
    virtual TaskFailureMessage *dup() const override {return new TaskFailureMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getFailure_time() const;
    virtual void setFailure_time(double failure_time);

    virtual const char * getFailure_reason() const;
    virtual void setFailure_reason(const char * failure_reason);

    virtual double getWasted_time() const;
    virtual void setWasted_time(double wasted_time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskFailureMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskFailureMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:86</tt> by opp_msgtool.
 * <pre>
 * //
 * // Vehicle Resource Status Message - Periodic heartbeat from vehicle to RSU
 * //
 * packet VehicleResourceStatusMessage extends BaseFrame1609_4
 * {
 *     LAddress::L2Type senderAddress = -1; // Sender's MAC address (set by vehicle via populateWSM)
 *     string vehicle_id;           // Vehicle identifier
 * 
 *     // Vehicle State
 *     double pos_x;                // Position X
 *     double pos_y;                // Position Y
 *     double speed;                // Current speed
 *     double acceleration;         // Current acceleration (m/s^2)
 *     double heading;              // Heading in degrees (0-360)
 * 
 *     // Resource Information
 *     double cpu_total;            // Total CPU capacity (Hz)
 *     double cpu_allocable;        // CPU available for tasks (after reservation)
 *     double cpu_available;        // Currently available CPU (Hz)
 *     double cpu_utilization;      // CPU utilization ratio (0.0-1.0)
 * 
 *     double mem_total;            // Total memory (bytes)
 *     double mem_available;        // Available memory (bytes)
 *     double mem_utilization;      // Memory utilization ratio (0.0-1.0)
 * 
 *     // Energy Information
 *     double battery_level_pct;    // Remaining battery percentage (0-100)
 *     double battery_current_mAh;  // Current battery charge (mAh)
 *     double battery_capacity_mAh; // Battery capacity (mAh)
 *     double energy_task_j_total;  // Cumulative task-related energy (J)
 *     double energy_task_j_last;   // Last task-related energy charge (J)
 * 
 *     // Task Queue Status
 *     uint32_t tasks_generated;    // Total tasks generated
 *     uint32_t tasks_completed_on_time;  // Tasks completed before deadline
 *     uint32_t tasks_completed_late;     // Tasks completed after deadline (soft miss)
 *     uint32_t tasks_failed;       // Tasks that missed deadline (hard miss)
 *     uint32_t tasks_rejected;     // Tasks rejected (queue full/infeasible)
 *     uint32_t current_queue_length;     // Current pending tasks
 *     uint32_t current_processing_count; // Currently processing tasks
 * 
 *     // Performance Metrics
 *     double avg_completion_time;  // Average task completion time
 *     double deadline_miss_ratio;  // Ratio of missed deadlines
 * }
 * </pre>
 */
class VehicleResourceStatusMessage : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type senderAddress = -1;
    ::omnetpp::opp_string vehicle_id;
    double pos_x = 0;
    double pos_y = 0;
    double speed = 0;
    double acceleration = 0;
    double heading = 0;
    double cpu_total = 0;
    double cpu_allocable = 0;
    double cpu_available = 0;
    double cpu_utilization = 0;
    double mem_total = 0;
    double mem_available = 0;
    double mem_utilization = 0;
    double battery_level_pct = 0;
    double battery_current_mAh = 0;
    double battery_capacity_mAh = 0;
    double energy_task_j_total = 0;
    double energy_task_j_last = 0;
    uint32_t tasks_generated = 0;
    uint32_t tasks_completed_on_time = 0;
    uint32_t tasks_completed_late = 0;
    uint32_t tasks_failed = 0;
    uint32_t tasks_rejected = 0;
    uint32_t current_queue_length = 0;
    uint32_t current_processing_count = 0;
    double avg_completion_time = 0;
    double deadline_miss_ratio = 0;

  private:
    void copy(const VehicleResourceStatusMessage& other);

  protected:
    bool operator==(const VehicleResourceStatusMessage&) = delete;

  public:
    VehicleResourceStatusMessage(const char *name=nullptr, short kind=0);
    VehicleResourceStatusMessage(const VehicleResourceStatusMessage& other);
    virtual ~VehicleResourceStatusMessage();
    VehicleResourceStatusMessage& operator=(const VehicleResourceStatusMessage& other);
    virtual VehicleResourceStatusMessage *dup() const override {return new VehicleResourceStatusMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<VehicleResourceStatusMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getPos_x() const;
    virtual void setPos_x(double pos_x);

    virtual double getPos_y() const;
    virtual void setPos_y(double pos_y);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getAcceleration() const;
    virtual void setAcceleration(double acceleration);

    virtual double getHeading() const;
    virtual void setHeading(double heading);

    virtual double getCpu_total() const;
    virtual void setCpu_total(double cpu_total);

    virtual double getCpu_allocable() const;
    virtual void setCpu_allocable(double cpu_allocable);

    virtual double getCpu_available() const;
    virtual void setCpu_available(double cpu_available);

    virtual double getCpu_utilization() const;
    virtual void setCpu_utilization(double cpu_utilization);

    virtual double getMem_total() const;
    virtual void setMem_total(double mem_total);

    virtual double getMem_available() const;
    virtual void setMem_available(double mem_available);

    virtual double getMem_utilization() const;
    virtual void setMem_utilization(double mem_utilization);

    virtual double getBattery_level_pct() const;
    virtual void setBattery_level_pct(double battery_level_pct);

    virtual double getBattery_current_mAh() const;
    virtual void setBattery_current_mAh(double battery_current_mAh);

    virtual double getBattery_capacity_mAh() const;
    virtual void setBattery_capacity_mAh(double battery_capacity_mAh);

    virtual double getEnergy_task_j_total() const;
    virtual void setEnergy_task_j_total(double energy_task_j_total);

    virtual double getEnergy_task_j_last() const;
    virtual void setEnergy_task_j_last(double energy_task_j_last);

    virtual uint32_t getTasks_generated() const;
    virtual void setTasks_generated(uint32_t tasks_generated);

    virtual uint32_t getTasks_completed_on_time() const;
    virtual void setTasks_completed_on_time(uint32_t tasks_completed_on_time);

    virtual uint32_t getTasks_completed_late() const;
    virtual void setTasks_completed_late(uint32_t tasks_completed_late);

    virtual uint32_t getTasks_failed() const;
    virtual void setTasks_failed(uint32_t tasks_failed);

    virtual uint32_t getTasks_rejected() const;
    virtual void setTasks_rejected(uint32_t tasks_rejected);

    virtual uint32_t getCurrent_queue_length() const;
    virtual void setCurrent_queue_length(uint32_t current_queue_length);

    virtual uint32_t getCurrent_processing_count() const;
    virtual void setCurrent_processing_count(uint32_t current_processing_count);

    virtual double getAvg_completion_time() const;
    virtual void setAvg_completion_time(double avg_completion_time);

    virtual double getDeadline_miss_ratio() const;
    virtual void setDeadline_miss_ratio(double deadline_miss_ratio);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VehicleResourceStatusMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VehicleResourceStatusMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:131</tt> by opp_msgtool.
 * <pre>
 * //
 * // Offloading Request Message - Task vehicle → RSU (requesting offloading decision)
 * //
 * packet OffloadingRequestMessage extends BaseFrame1609_4
 * {
 *     LAddress::L2Type senderAddress = -1; // Sender's MAC address
 *     string task_id;                      // Task identifier
 *     string vehicle_id;                   // Originating vehicle ID
 *     double request_time;                 // When request was sent
 * 
 *     // Task Characteristics
 *     uint64_t task_size_bytes;            // Legacy payload size field
 *     uint64_t mem_footprint_bytes;        // Working memory footprint
 *     uint64_t cpu_cycles;                 // Required CPU cycles
 *     double deadline_seconds;             // Task deadline
 *     double qos_value;                    // QoS priority
 * 
 *     // Vehicle State at Request Time
 *     double local_cpu_available_ghz;      // Available CPU (GHz)
 *     double local_cpu_utilization;        // CPU utilization (0-1)
 *     double local_mem_available_mb;       // Available memory (MB)
 *     uint32_t local_queue_length;         // Current queue length
 *     uint32_t local_processing_count;     // Current processing count
 * 
 *     // Vehicle Location
 *     double pos_x;
 *     double pos_y;
 *     double speed;
 * 
 *     // Local Decision Recommendation
 *     string local_decision;               // "LOCAL", "OFFLOAD", or "REJECT"
 * 
 *     // Ranked RSU Candidates (for redirect support)
 *     uint64_t candidate_rsu_macs[];       // Ordered list of candidate RSU MAC addresses (best to worst)
 *     int current_candidate_index;         // Index of current RSU being tried (0 = first/best)
 *     int max_redirect_hops;               // Maximum allowed redirects
 * }
 * </pre>
 */
class OffloadingRequestMessage : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type senderAddress = -1;
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    double request_time = 0;
    uint64_t task_size_bytes = 0;
    uint64_t mem_footprint_bytes = 0;
    uint64_t cpu_cycles = 0;
    double deadline_seconds = 0;
    double qos_value = 0;
    double local_cpu_available_ghz = 0;
    double local_cpu_utilization = 0;
    double local_mem_available_mb = 0;
    uint32_t local_queue_length = 0;
    uint32_t local_processing_count = 0;
    double pos_x = 0;
    double pos_y = 0;
    double speed = 0;
    ::omnetpp::opp_string local_decision;
    uint64_t *candidate_rsu_macs = nullptr;
    size_t candidate_rsu_macs_arraysize = 0;
    int current_candidate_index = 0;
    int max_redirect_hops = 0;

  private:
    void copy(const OffloadingRequestMessage& other);

  protected:
    bool operator==(const OffloadingRequestMessage&) = delete;

  public:
    OffloadingRequestMessage(const char *name=nullptr, short kind=0);
    OffloadingRequestMessage(const OffloadingRequestMessage& other);
    virtual ~OffloadingRequestMessage();
    OffloadingRequestMessage& operator=(const OffloadingRequestMessage& other);
    virtual OffloadingRequestMessage *dup() const override {return new OffloadingRequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<OffloadingRequestMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getRequest_time() const;
    virtual void setRequest_time(double request_time);

    virtual uint64_t getTask_size_bytes() const;
    virtual void setTask_size_bytes(uint64_t task_size_bytes);

    virtual uint64_t getMem_footprint_bytes() const;
    virtual void setMem_footprint_bytes(uint64_t mem_footprint_bytes);

    virtual uint64_t getCpu_cycles() const;
    virtual void setCpu_cycles(uint64_t cpu_cycles);

    virtual double getDeadline_seconds() const;
    virtual void setDeadline_seconds(double deadline_seconds);

    virtual double getQos_value() const;
    virtual void setQos_value(double qos_value);

    virtual double getLocal_cpu_available_ghz() const;
    virtual void setLocal_cpu_available_ghz(double local_cpu_available_ghz);

    virtual double getLocal_cpu_utilization() const;
    virtual void setLocal_cpu_utilization(double local_cpu_utilization);

    virtual double getLocal_mem_available_mb() const;
    virtual void setLocal_mem_available_mb(double local_mem_available_mb);

    virtual uint32_t getLocal_queue_length() const;
    virtual void setLocal_queue_length(uint32_t local_queue_length);

    virtual uint32_t getLocal_processing_count() const;
    virtual void setLocal_processing_count(uint32_t local_processing_count);

    virtual double getPos_x() const;
    virtual void setPos_x(double pos_x);

    virtual double getPos_y() const;
    virtual void setPos_y(double pos_y);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual const char * getLocal_decision() const;
    virtual void setLocal_decision(const char * local_decision);

    virtual void setCandidate_rsu_macsArraySize(size_t size);
    virtual size_t getCandidate_rsu_macsArraySize() const;
    virtual uint64_t getCandidate_rsu_macs(size_t k) const;
    virtual void setCandidate_rsu_macs(size_t k, uint64_t candidate_rsu_macs);
    virtual void insertCandidate_rsu_macs(size_t k, uint64_t candidate_rsu_macs);
    [[deprecated]] void insertCandidate_rsu_macs(uint64_t candidate_rsu_macs) {appendCandidate_rsu_macs(candidate_rsu_macs);}
    virtual void appendCandidate_rsu_macs(uint64_t candidate_rsu_macs);
    virtual void eraseCandidate_rsu_macs(size_t k);

    virtual int getCurrent_candidate_index() const;
    virtual void setCurrent_candidate_index(int current_candidate_index);

    virtual int getMax_redirect_hops() const;
    virtual void setMax_redirect_hops(int max_redirect_hops);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OffloadingRequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OffloadingRequestMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:168</tt> by opp_msgtool.
 * <pre>
 * //
 * // Offloading Decision Message - RSU → Task vehicle (ML model decision)
 * //
 * packet OffloadingDecisionMessage extends BaseFrame1609_4
 * {
 *     LAddress::L2Type senderAddress = -1; // RSU's MAC address
 *     string task_id;                      // Task identifier
 *     string vehicle_id;                   // Target vehicle ID
 *     double decision_time;                // When decision was made
 * 
 *     // Decision
 *     string decision_type;                // "LOCAL", "RSU", "SERVICE_VEHICLE", "REJECT", "REDIRECT", "ACCEPT"
 * 
 *     // If SERVICE_VEHICLE: target information
 *     string target_service_vehicle_id;    // Service vehicle ID (if applicable)
 *     uint64_t target_service_vehicle_mac; // Service vehicle MAC address (if applicable)
 * 
 *     // Optional RSU redirection hints for multi-hop offloading
 *     string redirect_target_rsu_id;       // Preferred RSU ID for forwarding
 *     uint64_t redirect_target_rsu_mac;    // Preferred RSU MAC for forwarding
 *     int next_candidate_index = 0;        // Candidate index hint for retry chains
 * 
 *     // Decision Metadata
 *     double confidence_score;             // ML model confidence (0-1)
 *     double estimated_completion_time;    // Estimated time to complete
 *     string decision_reason;              // Human-readable reasoning
 * 
 *     // Multi-agent baseline decisions (TV dispatches sub-tasks for each agent)
 *     // Encoded as CSV: "agent:TYPE:target_id:target_mac,..."
 *     // Example: "random:SERVICE_VEHICLE:42:318,greedy_comp:RSU:RSU_0:0,..."
 *     string agentDecisions;
 * }
 * </pre>
 */
class OffloadingDecisionMessage : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type senderAddress = -1;
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string vehicle_id;
    double decision_time = 0;
    ::omnetpp::opp_string decision_type;
    ::omnetpp::opp_string target_service_vehicle_id;
    uint64_t target_service_vehicle_mac = 0;
    ::omnetpp::opp_string redirect_target_rsu_id;
    uint64_t redirect_target_rsu_mac = 0;
    int next_candidate_index = 0;
    double confidence_score = 0;
    double estimated_completion_time = 0;
    ::omnetpp::opp_string decision_reason;
    ::omnetpp::opp_string agentDecisions;

  private:
    void copy(const OffloadingDecisionMessage& other);

  protected:
    bool operator==(const OffloadingDecisionMessage&) = delete;

  public:
    OffloadingDecisionMessage(const char *name=nullptr, short kind=0);
    OffloadingDecisionMessage(const OffloadingDecisionMessage& other);
    virtual ~OffloadingDecisionMessage();
    OffloadingDecisionMessage& operator=(const OffloadingDecisionMessage& other);
    virtual OffloadingDecisionMessage *dup() const override {return new OffloadingDecisionMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<OffloadingDecisionMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getDecision_time() const;
    virtual void setDecision_time(double decision_time);

    virtual const char * getDecision_type() const;
    virtual void setDecision_type(const char * decision_type);

    virtual const char * getTarget_service_vehicle_id() const;
    virtual void setTarget_service_vehicle_id(const char * target_service_vehicle_id);

    virtual uint64_t getTarget_service_vehicle_mac() const;
    virtual void setTarget_service_vehicle_mac(uint64_t target_service_vehicle_mac);

    virtual const char * getRedirect_target_rsu_id() const;
    virtual void setRedirect_target_rsu_id(const char * redirect_target_rsu_id);

    virtual uint64_t getRedirect_target_rsu_mac() const;
    virtual void setRedirect_target_rsu_mac(uint64_t redirect_target_rsu_mac);

    virtual int getNext_candidate_index() const;
    virtual void setNext_candidate_index(int next_candidate_index);

    virtual double getConfidence_score() const;
    virtual void setConfidence_score(double confidence_score);

    virtual double getEstimated_completion_time() const;
    virtual void setEstimated_completion_time(double estimated_completion_time);

    virtual const char * getDecision_reason() const;
    virtual void setDecision_reason(const char * decision_reason);

    virtual const char * getAgentDecisions() const;
    virtual void setAgentDecisions(const char * agentDecisions);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OffloadingDecisionMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OffloadingDecisionMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:200</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Offload Packet - Task vehicle → RSU/Service vehicle (complete task data)
 * //
 * packet TaskOffloadPacket extends BaseFrame1609_4
 * {
 *     string task_id;                      // Task identifier
 *     string origin_vehicle_id;            // Originating vehicle ID
 *     uint64_t origin_vehicle_mac;         // Return address MAC
 *     double offload_time;                 // When task was offloaded
 * 
 *     // Task Characteristics
 *     uint64_t task_size_bytes;            // Legacy payload size field
 *     uint64_t mem_footprint_bytes;        // Working memory footprint
 *     uint64_t cpu_cycles;                 // Required CPU cycles
 *     double deadline_seconds;             // Task deadline
 *     double qos_value;                    // QoS priority
 * 
 *     // Task Input Data (placeholder - would contain actual task data)
 *     string task_input_data;              // Serialized input data
 * }
 * </pre>
 */
class TaskOffloadPacket : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string origin_vehicle_id;
    uint64_t origin_vehicle_mac = 0;
    double offload_time = 0;
    uint64_t task_size_bytes = 0;
    uint64_t mem_footprint_bytes = 0;
    uint64_t cpu_cycles = 0;
    double deadline_seconds = 0;
    double qos_value = 0;
    ::omnetpp::opp_string task_input_data;

  private:
    void copy(const TaskOffloadPacket& other);

  protected:
    bool operator==(const TaskOffloadPacket&) = delete;

  public:
    TaskOffloadPacket(const char *name=nullptr, short kind=0);
    TaskOffloadPacket(const TaskOffloadPacket& other);
    virtual ~TaskOffloadPacket();
    TaskOffloadPacket& operator=(const TaskOffloadPacket& other);
    virtual TaskOffloadPacket *dup() const override {return new TaskOffloadPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getOrigin_vehicle_id() const;
    virtual void setOrigin_vehicle_id(const char * origin_vehicle_id);

    virtual uint64_t getOrigin_vehicle_mac() const;
    virtual void setOrigin_vehicle_mac(uint64_t origin_vehicle_mac);

    virtual double getOffload_time() const;
    virtual void setOffload_time(double offload_time);

    virtual uint64_t getTask_size_bytes() const;
    virtual void setTask_size_bytes(uint64_t task_size_bytes);

    virtual uint64_t getMem_footprint_bytes() const;
    virtual void setMem_footprint_bytes(uint64_t mem_footprint_bytes);

    virtual uint64_t getCpu_cycles() const;
    virtual void setCpu_cycles(uint64_t cpu_cycles);

    virtual double getDeadline_seconds() const;
    virtual void setDeadline_seconds(double deadline_seconds);

    virtual double getQos_value() const;
    virtual void setQos_value(double qos_value);

    virtual const char * getTask_input_data() const;
    virtual void setTask_input_data(const char * task_input_data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskOffloadPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskOffloadPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:220</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Result Message - RSU/Service vehicle → Task vehicle (processing results)
 * //
 * packet TaskResultMessage extends BaseFrame1609_4
 * {
 *     string task_id;                      // Task identifier
 *     string origin_vehicle_id;            // Original task vehicle ID
 *     string processor_id;                 // Who processed it ("RSU-X" or vehicle ID)
 *     double completion_time;              // When processing completed
 *     double processing_time;              // Actual processing duration
 *     bool success;                        // True if completed successfully
 * 
 *     // Results
 *     string task_output_data;             // Serialized output data
 *     string failure_reason;               // If failed, reason why
 * }
 * </pre>
 */
class TaskResultMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string origin_vehicle_id;
    ::omnetpp::opp_string processor_id;
    double completion_time = 0;
    double processing_time = 0;
    bool success = false;
    ::omnetpp::opp_string task_output_data;
    ::omnetpp::opp_string failure_reason;

  private:
    void copy(const TaskResultMessage& other);

  protected:
    bool operator==(const TaskResultMessage&) = delete;

  public:
    TaskResultMessage(const char *name=nullptr, short kind=0);
    TaskResultMessage(const TaskResultMessage& other);
    virtual ~TaskResultMessage();
    TaskResultMessage& operator=(const TaskResultMessage& other);
    virtual TaskResultMessage *dup() const override {return new TaskResultMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getOrigin_vehicle_id() const;
    virtual void setOrigin_vehicle_id(const char * origin_vehicle_id);

    virtual const char * getProcessor_id() const;
    virtual void setProcessor_id(const char * processor_id);

    virtual double getCompletion_time() const;
    virtual void setCompletion_time(double completion_time);

    virtual double getProcessing_time() const;
    virtual void setProcessing_time(double processing_time);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);

    virtual const char * getTask_output_data() const;
    virtual void setTask_output_data(const char * task_output_data);

    virtual const char * getFailure_reason() const;
    virtual void setFailure_reason(const char * failure_reason);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskResultMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskResultMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:236</tt> by opp_msgtool.
 * <pre>
 * //
 * // Task Offloading Event - Any entity → RSU (lifecycle tracking for Digital Twin)
 * //
 * packet TaskOffloadingEvent extends BaseFrame1609_4
 * {
 *     string task_id;                      // Task identifier
 *     string event_type;                   // "REQUEST_SENT", "DECISION_RECEIVED", "OFFLOAD_SENT", "PROCESSING_STARTED", "RESULT_RECEIVED", "TIMEOUT", etc.
 *     string source_entity_id;             // Who generated the event
 *     string target_entity_id;             // Target entity (if applicable)
 *     double event_time;                   // When event occurred
 *     string event_details;                // JSON with additional details
 * }
 * 
 * //
 * // RSU Status Broadcast Message - RSU → RSU neighbors (periodic state sharing)
 * //
 * </pre>
 */
class TaskOffloadingEvent : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string task_id;
    ::omnetpp::opp_string event_type;
    ::omnetpp::opp_string source_entity_id;
    ::omnetpp::opp_string target_entity_id;
    double event_time = 0;
    ::omnetpp::opp_string event_details;

  private:
    void copy(const TaskOffloadingEvent& other);

  protected:
    bool operator==(const TaskOffloadingEvent&) = delete;

  public:
    TaskOffloadingEvent(const char *name=nullptr, short kind=0);
    TaskOffloadingEvent(const TaskOffloadingEvent& other);
    virtual ~TaskOffloadingEvent();
    TaskOffloadingEvent& operator=(const TaskOffloadingEvent& other);
    virtual TaskOffloadingEvent *dup() const override {return new TaskOffloadingEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTask_id() const;
    virtual void setTask_id(const char * task_id);

    virtual const char * getEvent_type() const;
    virtual void setEvent_type(const char * event_type);

    virtual const char * getSource_entity_id() const;
    virtual void setSource_entity_id(const char * source_entity_id);

    virtual const char * getTarget_entity_id() const;
    virtual void setTarget_entity_id(const char * target_entity_id);

    virtual double getEvent_time() const;
    virtual void setEvent_time(double event_time);

    virtual const char * getEvent_details() const;
    virtual void setEvent_details(const char * event_details);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskOffloadingEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskOffloadingEvent& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TaskMetadataMessage.msg:250</tt> by opp_msgtool.
 * <pre>
 * // Vehicle detail information included in RSU broadcasts
 * class VehicleDetailInBroadcast
 * {
 *     string vehicle_id;                   // Vehicle identifier
 *     double pos_x;                        // Vehicle position X coordinate (meters)
 *     double pos_y;                        // Vehicle position Y coordinate (meters)
 *     double speed;                        // Vehicle speed (m/s)
 *     double heading;                      // Vehicle heading (degrees)
 *     double cpu_available;                // Available CPU (MIPS)
 *     double cpu_utilization;              // CPU utilization percentage (0-100)
 *     double mem_available;                // Available memory (MB)
 *     double mem_utilization;              // Memory utilization percentage (0-100)
 *     int queue_length;                    // Number of tasks in vehicle's queue
 * }
 * </pre>
 */
class VehicleDetailInBroadcast
{
  protected:
    ::omnetpp::opp_string vehicle_id;
    double pos_x = 0;
    double pos_y = 0;
    double speed = 0;
    double heading = 0;
    double cpu_available = 0;
    double cpu_utilization = 0;
    double mem_available = 0;
    double mem_utilization = 0;
    int queue_length = 0;

  private:
    void copy(const VehicleDetailInBroadcast& other);

  protected:
    bool operator==(const VehicleDetailInBroadcast&) = delete;

  public:
    VehicleDetailInBroadcast();
    VehicleDetailInBroadcast(const VehicleDetailInBroadcast& other);
    virtual ~VehicleDetailInBroadcast();
    VehicleDetailInBroadcast& operator=(const VehicleDetailInBroadcast& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    virtual const char * getVehicle_id() const;
    virtual void setVehicle_id(const char * vehicle_id);

    virtual double getPos_x() const;
    virtual void setPos_x(double pos_x);

    virtual double getPos_y() const;
    virtual void setPos_y(double pos_y);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getHeading() const;
    virtual void setHeading(double heading);

    virtual double getCpu_available() const;
    virtual void setCpu_available(double cpu_available);

    virtual double getCpu_utilization() const;
    virtual void setCpu_utilization(double cpu_utilization);

    virtual double getMem_available() const;
    virtual void setMem_available(double mem_available);

    virtual double getMem_utilization() const;
    virtual void setMem_utilization(double mem_utilization);

    virtual int getQueue_length() const;
    virtual void setQueue_length(int queue_length);
};

/**
 * Class generated from <tt>TaskMetadataMessage.msg:263</tt> by opp_msgtool.
 * <pre>
 * packet RSUStatusBroadcastMessage extends BaseFrame1609_4
 * {
 *     string rsu_id;                       // RSU identifier (e.g., "RSU_0")
 *     LAddress::L2Type rsu_mac;            // RSU MAC address
 *     double broadcast_time;               // When this status was broadcast
 * 
 *     // RSU Resource State
 *     int queue_length;                    // Current task queue length
 *     int processing_count;                // Currently processing tasks
 *     int max_concurrent_tasks;            // Maximum concurrent capacity
 *     double cpu_available_ghz;            // Available CPU (GHz)
 *     double cpu_total_ghz;                // Total CPU capacity (GHz)
 *     double memory_available_gb;          // Available memory (GB)
 *     double memory_total_gb;              // Total memory (GB)
 * 
 *     // Coverage Information with Vehicle Details
 *     VehicleDetailInBroadcast vehicle_details_in_coverage[];  // Full vehicle state in coverage
 *     string vehicle_ids_in_coverage[];    // Vehicle IDs in coverage
 *     int vehicle_count;                   // Number of vehicles in coverage
 * 
 *     // Network Topology
 *     double pos_x;                        // RSU position X
 *     double pos_y;                        // RSU position Y
 * }
 * </pre>
 */
class RSUStatusBroadcastMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string rsu_id;
    LAddress::L2Type rsu_mac;
    double broadcast_time = 0;
    int queue_length = 0;
    int processing_count = 0;
    int max_concurrent_tasks = 0;
    double cpu_available_ghz = 0;
    double cpu_total_ghz = 0;
    double memory_available_gb = 0;
    double memory_total_gb = 0;
    VehicleDetailInBroadcast *vehicle_details_in_coverage = nullptr;
    size_t vehicle_details_in_coverage_arraysize = 0;
    ::omnetpp::opp_string *vehicle_ids_in_coverage = nullptr;
    size_t vehicle_ids_in_coverage_arraysize = 0;
    int vehicle_count = 0;
    double pos_x = 0;
    double pos_y = 0;

  private:
    void copy(const RSUStatusBroadcastMessage& other);

  protected:
    bool operator==(const RSUStatusBroadcastMessage&) = delete;

  public:
    RSUStatusBroadcastMessage(const char *name=nullptr, short kind=0);
    RSUStatusBroadcastMessage(const RSUStatusBroadcastMessage& other);
    virtual ~RSUStatusBroadcastMessage();
    RSUStatusBroadcastMessage& operator=(const RSUStatusBroadcastMessage& other);
    virtual RSUStatusBroadcastMessage *dup() const override {return new RSUStatusBroadcastMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRsu_id() const;
    virtual void setRsu_id(const char * rsu_id);

    virtual const LAddress::L2Type& getRsu_mac() const;
    virtual LAddress::L2Type& getRsu_macForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<RSUStatusBroadcastMessage*>(this)->getRsu_mac());}
    virtual void setRsu_mac(const LAddress::L2Type& rsu_mac);

    virtual double getBroadcast_time() const;
    virtual void setBroadcast_time(double broadcast_time);

    virtual int getQueue_length() const;
    virtual void setQueue_length(int queue_length);

    virtual int getProcessing_count() const;
    virtual void setProcessing_count(int processing_count);

    virtual int getMax_concurrent_tasks() const;
    virtual void setMax_concurrent_tasks(int max_concurrent_tasks);

    virtual double getCpu_available_ghz() const;
    virtual void setCpu_available_ghz(double cpu_available_ghz);

    virtual double getCpu_total_ghz() const;
    virtual void setCpu_total_ghz(double cpu_total_ghz);

    virtual double getMemory_available_gb() const;
    virtual void setMemory_available_gb(double memory_available_gb);

    virtual double getMemory_total_gb() const;
    virtual void setMemory_total_gb(double memory_total_gb);

    virtual void setVehicle_details_in_coverageArraySize(size_t size);
    virtual size_t getVehicle_details_in_coverageArraySize() const;
    virtual const VehicleDetailInBroadcast& getVehicle_details_in_coverage(size_t k) const;
    virtual VehicleDetailInBroadcast& getVehicle_details_in_coverageForUpdate(size_t k) { return const_cast<VehicleDetailInBroadcast&>(const_cast<RSUStatusBroadcastMessage*>(this)->getVehicle_details_in_coverage(k));}
    virtual void setVehicle_details_in_coverage(size_t k, const VehicleDetailInBroadcast& vehicle_details_in_coverage);
    virtual void insertVehicle_details_in_coverage(size_t k, const VehicleDetailInBroadcast& vehicle_details_in_coverage);
    [[deprecated]] void insertVehicle_details_in_coverage(const VehicleDetailInBroadcast& vehicle_details_in_coverage) {appendVehicle_details_in_coverage(vehicle_details_in_coverage);}
    virtual void appendVehicle_details_in_coverage(const VehicleDetailInBroadcast& vehicle_details_in_coverage);
    virtual void eraseVehicle_details_in_coverage(size_t k);

    virtual void setVehicle_ids_in_coverageArraySize(size_t size);
    virtual size_t getVehicle_ids_in_coverageArraySize() const;
    virtual const char * getVehicle_ids_in_coverage(size_t k) const;
    virtual void setVehicle_ids_in_coverage(size_t k, const char * vehicle_ids_in_coverage);
    virtual void insertVehicle_ids_in_coverage(size_t k, const char * vehicle_ids_in_coverage);
    [[deprecated]] void insertVehicle_ids_in_coverage(const char * vehicle_ids_in_coverage) {appendVehicle_ids_in_coverage(vehicle_ids_in_coverage);}
    virtual void appendVehicle_ids_in_coverage(const char * vehicle_ids_in_coverage);
    virtual void eraseVehicle_ids_in_coverage(size_t k);

    virtual int getVehicle_count() const;
    virtual void setVehicle_count(int vehicle_count);

    virtual double getPos_x() const;
    virtual void setPos_x(double pos_x);

    virtual double getPos_y() const;
    virtual void setPos_y(double pos_y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RSUStatusBroadcastMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RSUStatusBroadcastMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::TaskMetadataMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskMetadataMessage*>(ptr.get<cObject>()); }
template<> inline veins::ObjectDetectionDataMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::ObjectDetectionDataMessage*>(ptr.get<cObject>()); }
template<> inline veins::TaskCompletionMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskCompletionMessage*>(ptr.get<cObject>()); }
template<> inline veins::TaskFailureMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskFailureMessage*>(ptr.get<cObject>()); }
template<> inline veins::VehicleResourceStatusMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::VehicleResourceStatusMessage*>(ptr.get<cObject>()); }
template<> inline veins::OffloadingRequestMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::OffloadingRequestMessage*>(ptr.get<cObject>()); }
template<> inline veins::OffloadingDecisionMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::OffloadingDecisionMessage*>(ptr.get<cObject>()); }
template<> inline veins::TaskOffloadPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskOffloadPacket*>(ptr.get<cObject>()); }
template<> inline veins::TaskResultMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskResultMessage*>(ptr.get<cObject>()); }
template<> inline veins::TaskOffloadingEvent *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TaskOffloadingEvent*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const veins::VehicleDetailInBroadcast *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline veins::VehicleDetailInBroadcast *fromAnyPtr(any_ptr ptr) { return ptr.get<veins::VehicleDetailInBroadcast>(); }
template<> inline veins::RSUStatusBroadcastMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::RSUStatusBroadcastMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_TASKMETADATAMESSAGE_M_H

